#include <iostream>
#include <vector>
#include <memory>
#include <list>
#include <string>
#include <assert.h>
#include <tuple>
#include <variant>
#include <array>
#include <unordered_set>
#include <unordered_map>
#include <functional>
#include <algorithm>
